export const MAPBOX_READY = "MAPBOX_READY";
export const RESIZE_WINDOW = "RESIZE_WINDOW";
export const MAPBOX_VIEWPORT_CHANGE = "MAPBOX_VIEWPORT_CHANGE";
export const CHANGE_FLOOR = "CHANGE_FLOOR";
export const SHOW_INFOBLOCK = "SHOW_INFOBLOCK";
export const HIDE_INFOBLOCK = "HIDE_INFOBLOCK";